### ISSUE TITLE
1.1  - Correção do cadastro ao consultar CEP

### ISSUE THREAD

**Issue by fjcs7** [fjcs7/EasyFesta#5]
Pelo fato de que nossa aplicação esteja atualmente hospedada e um servidor com segurança elevada, no caso https, existe uma integração com terceiros para consultar dados de CEP que utiliza uma chamada a um servidor não seguro HTTP, o que não está sendo aceito pelo nosso servidor atual.

Verificar se existe algum servidor compatível com a chamada que aceite HTTPS como chamada.

**Comment by AlexCruzeiro** [comment]
Issue resolvida no commit https://github.com/fjcs7/EasyFesta/commit/a2e8b05a86314dc97692ab18f200a8b7d688d5f0
